name: Publish
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '16'
    steps:
    - name: Echo environment
      run: echo "nodejs $(node -v), npm v$(npm -v)"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run tests
      run: npm t
    - name: Check syntax
      run: npm run lint -- --plugin log
    - name: Add NPM token
      if: github.ref == 'refs/heads/main'
      run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build and Publish
      if: github.ref == 'refs/heads/main'
      run: npx @lets/publish
